version: "3.4"
services:
  neko:
    image: "localhost/neko-jverein"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_NAT1TO1: 127.0.0.1
    volumes:
      - ./data/:/home/neko/.jameica/
      - ./nextcloud/:/home/neko/.jameica/data/attachments
  database:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: neko
